version: '3.8'

services:
  postgres-user:
    image: postgres:16-alpine
    container_name: postgres-user
    environment:
      POSTGRES_USER: user_db_user
      POSTGRES_PASSWORD: user_db_password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - ecom-network

  postgres-product:
    image: postgres:16-alpine
    container_name: postgres-product
    environment:
      POSTGRES_USER: product_db_user
      POSTGRES_PASSWORD: product_db_password
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    networks:
      - ecom-network

  postgres-order:
    image: postgres:16-alpine
    container_name: postgres-order
    environment:
      POSTGRES_USER: order_db_user
      POSTGRES_PASSWORD: order_db_password
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - ecom-network

volumes:
  postgres-user-data:
  postgres-product-data:
  postgres-order-data:

networks:
  ecom-network:
    driver: bridge
